### ISSUE TITLE
Issue after Build the linux kernel 

### ISSUE THREAD

**Issue by FlyBoyA** [shkwon98/rpi4_preemptRT#1]
After doing 

```
make -j4 zImage 
make -j4 modules 
make -j4 dtbs 

```
I get error at this step do you have idea what could be the issue
`make -j4 modules_install `

I have attached the error snapshot
![dtbs](https://github.com/shkwon98/rpi4-preemptrt/assets/124587223/9d77ff2d-2355-42e3-8ed6-229f1a3c80f8)

**Comment by shkwon98** [comment]
@FlyBoyA 
I don't know the entire process you had done. So please understand that I can only give very limited answer to your question. Looking at the file paths shown during the make command, there is a possibility that the shell's environment variables are not set correctly. Please enter the series of commands again sequentially without closing or moving the terminal in the middle.

**Comment by shkwon98** [comment]
As not any more activities, closing this issue.
